Reduce some codacy issues #2
aviaryan/Hinix pull request #66
Opened 2016-10-17 21:23 UTC by darkwizz

To #41

2016-10-18 03:44 UTC, aviaryan requested changes

2016-10-18 03:44 UTC, aviaryan commented on app/src/main/java/in/aviaryan/hinix/GameBoard.java
> +    private boolean hasBadLetters(String word, String badLetters) {
Can you please move badLetters inside this function and not pass it as a parameter. Or better, make it a final class variable.

2016-10-18 06:14 UTC, darkwizz commented on app/src/main/java/in/aviaryan/hinix/GameBoard.java
> +    private boolean hasBadLetters(String word, String badLetters) {
done

2016-10-18 06:16 UTC, aviaryan approved these changes

2016-10-20 11:33 UTC, aviaryan commented
@darkwizz The app crashes when I run it. Please fix this issue.

2016-10-20 11:34 UTC, aviaryan requested changes
The app crashes when I run it. Please fix this issue.

2016-10-20 19:01 UTC, darkwizz commented
ok

2016-10-21 00:10 UTC, darkwizz commented
fixed

2016-12-06 18:42 UTC, closed without merging