Added new instruction in startscreen
aviaryan/Hinix pull request #90
Opened 2017-06-04 17:56 UTC by Monal5031

2017-06-04 18:31 UTC, aviaryan requested changes

2017-06-04 18:31 UTC, aviaryan commented on app/src/main/res/values/strings.xml
> +        \n4. You can select letters adjacent to currently selected letter's only.
Make this the 2nd point and `letter's` should be `letters`.  Also adjacent is not a correct term as it doesn't represent squares sharing a vertex.

2017-06-05 11:14 UTC, aviaryan requested changes

2017-06-05 11:14 UTC, aviaryan commented on app/src/main/res/values/strings.xml
> +        \n4. You can select letters joining currently selected letters only.
Please make this the 2nd point as it is best suited after 1st point.

2017-06-05 11:32 UTC, Monal5031 commented on app/src/main/res/values/strings.xml
> +        \n4. You can select letters joining currently selected letters only.
Yes will do it, also the `letters` should be `letter`. Reason is I tested the app again we can only select the letter which is next to only the previously selected letter.

2017-06-05 11:36 UTC, aviaryan commented on app/src/main/res/values/strings.xml
> +        \n4. You can select letters joining currently selected letters only.
...you can select letters such that consecutive letters are neighbour to one another

2017-06-05 14:51 UTC, aviaryan requested changes
😆

2017-06-05 14:51 UTC, aviaryan commented on app/src/main/res/values/strings.xml
> +        \n2. You can onyl select letters such that consecutive letters are neighbour to one another.
onyl

2017-06-06 02:59 UTC, aviaryan approved these changes
✅

2017-06-06 02:59 UTC, merged